CREATE OR ALTER PROCEDURE sp_cargar_dw
AS
BEGIN

-- ======================
-- LIMPIAR DIMENSIONES
-- ======================

DELETE FROM dim.DIM_CLIENTE
DELETE FROM dim.DIM_TIPO_CONTRATO
DELETE FROM dim.DIM_MERCADO
DELETE FROM dim.DIM_DIVISION
DELETE FROM dim.DIM_FRECUENCIA
DELETE FROM dim.DIM_FECHA
DELETE FROM dim.DIM_TIPO_CENTRAL
DELETE FROM dim.DIM_CENTRAL
DELETE FROM dim.DIM_CONCEPTO

-- ======================
-- CARGAR DIMENSIONES
-- ======================

INSERT INTO dim.DIM_CLIENTE
SELECT DISTINCT * FROM stg.DIM_CLIENTE

INSERT INTO dim.DIM_TIPO_CONTRATO
SELECT DISTINCT * FROM stg.DIM_TIPO_CONTRATO

INSERT INTO dim.DIM_MERCADO
SELECT DISTINCT * FROM stg.DIM_MERCADO

INSERT INTO dim.DIM_DIVISION
SELECT DISTINCT * FROM stg.DIM_DIVISION

INSERT INTO dim.DIM_FRECUENCIA
SELECT DISTINCT * FROM stg.DIM_FRECUENCIA

INSERT INTO dim.DIM_FECHA
SELECT DISTINCT * FROM stg.DIM_FECHA

INSERT INTO dim.DIM_TIPO_CENTRAL
SELECT DISTINCT * FROM stg.DIM_TIPO_CENTRAL

INSERT INTO dim.DIM_CENTRAL
SELECT DISTINCT * FROM stg.DIM_CENTRAL

INSERT INTO dim.DIM_CONCEPTO
SELECT DISTINCT * FROM stg.DIM_CONCEPTO

-- ======================
-- TABLAS OPERATIVAS
-- ======================

DELETE FROM dbo.ACTIVIDAD
DELETE FROM dbo.CONTRATO

INSERT INTO dbo.ACTIVIDAD
SELECT *
FROM stg.ACTIVIDAD

INSERT INTO dbo.CONTRATO
SELECT *
FROM stg.CONTRATO

-- ======================
-- LIMPIAR FACT
-- ======================

DELETE FROM fact.FACT_VENTA
DELETE FROM fact.FACT_COMPRA
DELETE FROM fact.FACT_PRODUCCION
DELETE FROM fact.FACT_CONSUMO_TIPO_CENTRAL
DELETE FROM fact.FACT_MOVIMIENTO_CONCEPTO
DELETE FROM fact.FACT_INDICADOR_MENSUAL

-- ======================
-- CARGAR FACT
-- ======================

INSERT INTO fact.FACT_VENTA
SELECT * FROM stg.FACT_VENTA

INSERT INTO fact.FACT_COMPRA
SELECT * FROM stg.FACT_COMPRA

INSERT INTO fact.FACT_PRODUCCION
SELECT * FROM stg.FACT_PRODUCCION

INSERT INTO fact.FACT_CONSUMO_TIPO_CENTRAL
SELECT * FROM stg.FACT_CONSUMO_TIPO_CENTRAL

INSERT INTO fact.FACT_MOVIMIENTO_CONCEPTO
SELECT * FROM stg.FACT_MOVIMIENTO_CONCEPTO

INSERT INTO fact.FACT_INDICADOR_MENSUAL
SELECT * FROM stg.FACT_INDICADOR_MENSUAL

END