CREATE DATABASE DATA_WAREHOUSE;
GO

USE DATA_WAREHOUSE;
GO

CREATE SCHEMA stg;
GO
CREATE SCHEMA dim;
GO
CREATE SCHEMA fact;
GO

ALTER DATABASE DATA_WAREHOUSE SET RECOVERY SIMPLE;
GO
ALTER DATABASE DATA_WAREHOUSE SET READ_COMMITTED_SNAPSHOT ON;
GO

SELECT name
FROM sys.schemas
WHERE name IN ('stg', 'dim', 'fact');

SELECT name
FROM sys.databases
WHERE name = 'DATA_WAREHOUSE';

/*DIMENSIONES*/

CREATE TABLE dim.DIM_CLIENTE (
    ID_CLIENTE INT PRIMARY KEY,
    NOMBRE_CLIENTE VARCHAR(200)
);

CREATE TABLE dim.DIM_TIPO_CONTRATO (
    ID_TIPO_CONTRATO INT PRIMARY KEY,
    CODIGO_TIPO_CONTRATO VARCHAR(20),
    DESCRIPCION_TIPO_CONTRATO VARCHAR(100)
);

CREATE TABLE dim.DIM_MERCADO (
    ID_MERCADO INT PRIMARY KEY,
    CODIGO_MERCADO VARCHAR(20),
    DESCRIPCION_MERCADO VARCHAR(100)
);

CREATE TABLE dim.DIM_DIVISION (
    ID_DIVISION INT PRIMARY KEY,
    NOMBRE_DIVISION VARCHAR(150)
);

CREATE TABLE dim.DIM_FRECUENCIA (
    ID_FRECUENCIA INT PRIMARY KEY,
    NOMBRE_FRECUENCIA VARCHAR(100)
);

CREATE TABLE dim.DIM_FECHA (
    ID_FECHA INT PRIMARY KEY,
    FECHA DATE,
    ANIO INT,
    MES INT,
    DIA INT,
    TRIMESTRE INT,
    ANIO_MES INT,
    NOMBRE_MES VARCHAR(20),
    DIA_SEMANA VARCHAR(20),
    ES_FIN_SEMANA BIT
);

CREATE TABLE dim.DIM_TIPO_CENTRAL (
    ID_TIPO_CENTRAL INT PRIMARY KEY,
    CODIGO_TIPO_CENTRAL VARCHAR(20),
    DESCRIPCION_TIPO_CENTRAL VARCHAR(100)
);

CREATE TABLE dim.DIM_CENTRAL (
    ID_CENTRAL INT PRIMARY KEY,
    ID_TIPO_CENTRAL INT,
    CODIGO_CENTRAL VARCHAR(20),
    NOMBRE_CENTRAL VARCHAR(150)
);

CREATE TABLE dim.DIM_CONCEPTO (
    ID_CONCEPTO INT PRIMARY KEY,
    CODIGO_CONCEPTO VARCHAR(20),
    DESCRIPCION_CONCEPTO VARCHAR(200),
    TIPO_FLUJO VARCHAR(20),
    SIGNO INT
);

/*HECHOS*/

CREATE TABLE dbo.CONTRATO (
    ID_CONTRATO INT NOT NULL PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    ID_TIPO_CONTRATO INT NOT NULL,
    ID_MERCADO INT NOT NULL,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,

    CONSTRAINT FK_CONTRATO_CLIENTE
        FOREIGN KEY (ID_CLIENTE)
        REFERENCES dim.DIM_CLIENTE(ID_CLIENTE),

    CONSTRAINT FK_CONTRATO_TIPO
        FOREIGN KEY (ID_TIPO_CONTRATO)
        REFERENCES dim.DIM_TIPO_CONTRATO(ID_TIPO_CONTRATO),

    CONSTRAINT FK_CONTRATO_MERCADO
        FOREIGN KEY (ID_MERCADO)
        REFERENCES dim.DIM_MERCADO(ID_MERCADO)
);

CREATE TABLE dbo.ACTIVIDAD (
    ID_ACTIVIDAD INT NOT NULL PRIMARY KEY,
    NOMBRE_ACTIVIDAD VARCHAR(200),
    ID_DIVISION INT NOT NULL,
    ID_FRECUENCIA INT NOT NULL,

    CONSTRAINT FK_ACTIVIDAD_DIVISION
        FOREIGN KEY (ID_DIVISION)
        REFERENCES dim.DIM_DIVISION(ID_DIVISION),

    CONSTRAINT FK_ACTIVIDAD_FRECUENCIA
        FOREIGN KEY (ID_FRECUENCIA)
        REFERENCES dim.DIM_FRECUENCIA(ID_FRECUENCIA)
);

CREATE TABLE fact.FACT_VENTA (
    ID_VENTA INT PRIMARY KEY,
    ID_CONTRATO INT,
    ID_FECHA INT,
    ENERGIA_MWH DECIMAL(18,4),
    IMPORTE_SOLES DECIMAL(18,4),
    TARIFA_USD_MWH DECIMAL(18,4),

    FOREIGN KEY (ID_FECHA)
    REFERENCES dim.DIM_FECHA(ID_FECHA)
);

CREATE TABLE fact.FACT_COMPRA (
    ID_COMPRA INT PRIMARY KEY,
    ID_CONTRATO INT,
    ID_FECHA INT,
    ENERGIA_MWH DECIMAL(18,4),
    IMPORTE_SOLES DECIMAL(18,4),

    FOREIGN KEY (ID_FECHA)
    REFERENCES dim.DIM_FECHA(ID_FECHA)
);

CREATE TABLE fact.FACT_PRODUCCION (
    ID_PRODUCCION INT PRIMARY KEY,
    ID_CENTRAL INT,
    ID_FECHA INT,
    ENERGIA_MWH DECIMAL(18,4),

    FOREIGN KEY (ID_FECHA)
    REFERENCES dim.DIM_FECHA(ID_FECHA),

    FOREIGN KEY (ID_CENTRAL)
    REFERENCES dim.DIM_CENTRAL(ID_CENTRAL)
);

CREATE TABLE fact.FACT_CONSUMO_TIPO_CENTRAL (
    ID_CONSUMO INT PRIMARY KEY,
    ID_TIPO_CENTRAL INT,
    ID_FECHA INT,
    ENERGIA_MWH DECIMAL(18,4),

    FOREIGN KEY (ID_FECHA)
    REFERENCES dim.DIM_FECHA(ID_FECHA),

    FOREIGN KEY (ID_TIPO_CENTRAL)
    REFERENCES dim.DIM_TIPO_CENTRAL(ID_TIPO_CENTRAL)
);

CREATE TABLE fact.FACT_MOVIMIENTO_CONCEPTO (
    ID_MOVIMIENTO INT PRIMARY KEY,
    ID_CONCEPTO INT,
    ID_FECHA INT,
    IMPORTE_SOLES DECIMAL(18,4),

    FOREIGN KEY (ID_FECHA)
    REFERENCES dim.DIM_FECHA(ID_FECHA),

    FOREIGN KEY (ID_CONCEPTO)
    REFERENCES dim.DIM_CONCEPTO(ID_CONCEPTO)
);

CREATE TABLE fact.FACT_INDICADOR_MENSUAL (
    ID_INDICADOR INT PRIMARY KEY,
    ID_FECHA INT,
    CAUDAL_PROMEDIO DECIMAL(18,4),
    CMG_PROMEDIO DECIMAL(18,4),
    TIPO_CAMBIO_PROMEDIO DECIMAL(18,4),

    FOREIGN KEY (ID_FECHA)
    REFERENCES dim.DIM_FECHA(ID_FECHA)
);

/*STAGING*/

CREATE TABLE stg.DIM_CLIENTE (
    ID_CLIENTE INT,
    NOMBRE_CLIENTE VARCHAR(150)
);

CREATE TABLE stg.DIM_TIPO_CONTRATO (
    ID_TIPO_CONTRATO INT,
    CODIGO_TIPO_CONTRATO VARCHAR(20),
    DESCRIPCION_TIPO_CONTRATO VARCHAR(100)
);

CREATE TABLE stg.DIM_MERCADO (
    ID_MERCADO INT,
    CODIGO_MERCADO VARCHAR(20),
    DESCRIPCION_MERCADO VARCHAR(100)
);

CREATE TABLE stg.DIM_TIPO_CENTRAL (
    ID_TIPO_CENTRAL INT,
    CODIGO_TIPO_CENTRAL VARCHAR(20),
    DESCRIPCION_TIPO_CENTRAL VARCHAR(100)
);

CREATE TABLE stg.DIM_CENTRAL (
    ID_CENTRAL INT,
    ID_TIPO_CENTRAL INT,
    CODIGO_CENTRAL VARCHAR(20),
    NOMBRE_CENTRAL VARCHAR(150)
);

CREATE TABLE stg.DIM_CONCEPTO (
    ID_CONCEPTO INT,
    CODIGO_CONCEPTO VARCHAR(20),
    DESCRIPCION_CONCEPTO VARCHAR(200),
    TIPO_FLUJO VARCHAR(20),
    SIGNO INT
);

CREATE TABLE stg.DIM_DIVISION (
    ID_DIVISION INT,
    NOMBRE_DIVISION VARCHAR(150)
);

CREATE TABLE stg.DIM_FRECUENCIA (
    ID_FRECUENCIA INT,
    NOMBRE_FRECUENCIA VARCHAR(100)
);

CREATE TABLE stg.DIM_FECHA (
    ID_FECHA INT,
    FECHA DATE,
    ANIO INT,
    MES INT,
    DIA INT,
    TRIMESTRE INT,
    ANIO_MES INT,
    NOMBRE_MES VARCHAR(15),
    DIA_SEMANA VARCHAR(15),
    ES_FIN_SEMANA BIT
);

CREATE TABLE stg.CONTRATO (
    ID_CONTRATO INT,
    ID_CLIENTE INT,
    ID_TIPO_CONTRATO INT,
    ID_MERCADO INT,
    FECHA_INICIO DATE,
    FECHA_FIN DATE
);

CREATE TABLE stg.ACTIVIDAD (
    ID_ACTIVIDAD INT,
    ACTIVIDAD_CORTA VARCHAR(200),
    ACTIVIDAD VARCHAR(300),
    ID_DIVISION INT,
    ID_FRECUENCIA INT,
    CRITICIDAD VARCHAR(50),
    DESTINO VARCHAR(200),
    ESTADO VARCHAR(50),
    DIAS_ALERTA INT
);

CREATE TABLE stg.FACT_VENTA (
    ID_VENTA INT,
    ID_CONTRATO INT,
    ID_FECHA INT,
    ENERGIA_MWH DECIMAL(18,4),
    IMPORTE_SOLES DECIMAL(18,2),
    TARIFA_USD_MWH DECIMAL(18,4)
);

CREATE TABLE stg.FACT_COMPRA (
    ID_COMPRA INT,
    ID_CONTRATO INT,
    ID_FECHA INT,
    ENERGIA_MWH DECIMAL(18,4),
    IMPORTE_SOLES DECIMAL(18,2)
);

CREATE TABLE stg.FACT_PRODUCCION (
    ID_PRODUCCION INT,
    ID_CENTRAL INT,
    ID_FECHA INT,
    ENERGIA_MWH DECIMAL(18,4)
);

CREATE TABLE stg.FACT_CONSUMO_TIPO_CENTRAL (
    ID_CONSUMO INT,
    ID_TIPO_CENTRAL INT,
    ID_FECHA INT,
    ENERGIA_MWH DECIMAL(18,4)
);

CREATE TABLE stg.FACT_MOVIMIENTO_CONCEPTO (
    ID_MOVIMIENTO INT,
    ID_CONCEPTO INT,
    ID_FECHA INT,
    IMPORTE_SOLES DECIMAL(18,2)
);

CREATE TABLE stg.FACT_INDICADOR_MENSUAL (
    ID_INDICADOR INT,
    ID_FECHA INT,
    CAUDAL_PROMEDIO DECIMAL(18,4),
    CMG_PROMEDIO DECIMAL(18,4),
    TIPO_CAMBIO_PROMEDIO DECIMAL(18,4)
);

SELECT COUNT(*) FROM stg.DIM_CLIENTE;
SELECT COUNT(*) FROM stg.DIM_FECHA;
SELECT COUNT(*) FROM stg.FACT_VENTA;

INSERT INTO dim.DIM_CLIENTE
SELECT * FROM stg.DIM_CLIENTE;

INSERT INTO dim.DIM_TIPO_CONTRATO
SELECT * FROM stg.DIM_TIPO_CONTRATO;

INSERT INTO dim.DIM_MERCADO
SELECT * FROM stg.DIM_MERCADO;

INSERT INTO dim.DIM_DIVISION
SELECT * FROM stg.DIM_DIVISION;

INSERT INTO dim.DIM_FRECUENCIA
SELECT * FROM stg.DIM_FRECUENCIA;

INSERT INTO dim.DIM_FECHA
SELECT * FROM stg.DIM_FECHA;

INSERT INTO dim.DIM_TIPO_CENTRAL
SELECT * FROM stg.DIM_TIPO_CENTRAL;

INSERT INTO dim.DIM_CENTRAL
SELECT * FROM stg.DIM_CENTRAL;

INSERT INTO dim.DIM_CONCEPTO
SELECT * FROM stg.DIM_CONCEPTO;

SELECT COUNT(*) FROM dim.DIM_CLIENTE;
SELECT COUNT(*) FROM dim.DIM_FECHA;
SELECT COUNT(*) FROM dim.DIM_CENTRAL;

INSERT INTO fact.FACT_VENTA
SELECT * FROM stg.FACT_VENTA;

INSERT INTO fact.FACT_COMPRA
SELECT * FROM stg.FACT_COMPRA;

INSERT INTO fact.FACT_PRODUCCION
SELECT * FROM stg.FACT_PRODUCCION;

INSERT INTO fact.FACT_CONSUMO_TIPO_CENTRAL
SELECT * FROM stg.FACT_CONSUMO_TIPO_CENTRAL;

INSERT INTO fact.FACT_MOVIMIENTO_CONCEPTO
SELECT * FROM stg.FACT_MOVIMIENTO_CONCEPTO;

INSERT INTO fact.FACT_INDICADOR_MENSUAL
SELECT * FROM stg.FACT_INDICADOR_MENSUAL;

SELECT COUNT(*) FROM fact.FACT_VENTA;
SELECT COUNT(*) FROM fact.FACT_COMPRA;
SELECT COUNT(*) FROM fact.FACT_PRODUCCION;

SELECT TOP 10 *
FROM fact.FACT_VENTA v
JOIN dim.DIM_FECHA f
ON v.ID_FECHA = f.ID_FECHA

SELECT
    f.ANIO,
    SUM(v.ENERGIA_MWH) AS ENERGIA_VENDIDA
FROM fact.FACT_VENTA v
JOIN dim.DIM_FECHA f
ON v.ID_FECHA = f.ID_FECHA
GROUP BY f.ANIO
ORDER BY f.ANIO;